import ply.yacc as yacc

# parser.py - Parses the tokens generated by the lexer and constructs the JSON data structure#
# parser.py - Parses the tokens generated by the lexer
# and constructs the JSON data structure
