name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: python:3.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run unit tests
        run: |
          pytest ./test_py/test_*.py

      - name: Run json_parser.py with test JSON files
        run: |
          for file in tests/**/*.json; do
            python cc_json/json_parser.py "$file"
          done
